/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

import data.Codes;
import data.UserPreferences;
import secure.Network;
import static secure.Network.request;
import static secure.Network.session;

/**
 *
 * @author Aarib
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        // Get user preferences and set up login screen
        if (UserPreferences.isAutoLogin() || UserPreferences.isUserRemembered()) {
            // Automatically type in user name
            txtUsername.setText(UserPreferences.getStoredUser());
            chkRemember.setSelected(true);
            chkAutomatic.setEnabled(true);
            
            if (UserPreferences.isAutoLogin()) {
                // Automatically type in password
                txtPassword.setText(UserPreferences.getStoredPassword());
                
                // Lock password from modification / copying
                txtPassword.setEnabled(false);
                
                chkAutomatic.setSelected(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        chkAutomatic = new javax.swing.JCheckBox();
        chkRemember = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        jLabel1.setText("User Name:");

        jLabel2.setText("Password:");

        chkAutomatic.setText("Automatically log me in");
        chkAutomatic.setEnabled(false);
        chkAutomatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAutomaticActionPerformed(evt);
            }
        });

        chkRemember.setText("Remember me");
        chkRemember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRememberActionPerformed(evt);
            }
        });

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkRemember)
                            .addComponent(chkAutomatic))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(chkRemember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkAutomatic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkRememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRememberActionPerformed
        if (chkRemember.isSelected()) {
            chkAutomatic.setEnabled(true);
            
            UserPreferences.setRememberedUser(txtUsername.getText());
        } else {
            chkAutomatic.setSelected(false);
            chkAutomatic.setEnabled(false);
            
            UserPreferences.removeAutoLogin();
            UserPreferences.removeRememberedUser();
        }
    }//GEN-LAST:event_chkRememberActionPerformed

    private void chkAutomaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAutomaticActionPerformed
        if (chkAutomatic.isSelected()) {
            UserPreferences.setAutoLogin(Network.md5(new String(txtPassword.getPassword())));
        } else {
            UserPreferences.removeAutoLogin();
            txtPassword.setEnabled(true);
        }
    }//GEN-LAST:event_chkAutomaticActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String packet = "";
        packet += Codes.REQUEST_AUTHORIZATION + " ";
        packet += txtUsername.getText() + " ";
        if (UserPreferences.isAutoLogin()) {
            packet += UserPreferences.getStoredPassword();
        } else {
            packet += Network.md5(new String(txtPassword.getPassword()));
        }
        
        String sessionResponse = request(packet);
        String[] responseTokens = sessionResponse.split(" ");

        if (responseTokens[0].equals(""+Codes.RESPONSE_SUCCESS)) {
            Network.username = txtUsername.getText();
            session = responseTokens[1];
            System.out.println("Sucessfully logged in");

            Home.self.remove(this);
            Home.self.loadWorld();
        } else {
            System.out.println("Failed with error code: " + sessionResponse);
        }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chkAutomatic;
    private javax.swing.JCheckBox chkRemember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
